package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-22T18:30:26.340+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "GetPnrPermission", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/Getpnrpermission.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class GetPnrPermission extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "GetPnrPermission");
    public final static QName GetPnrPermissionSoap = new QName("http://tempuri.org/", "GetPnrPermissionSoap");
    public final static QName GetPnrPermissionSoap12 = new QName("http://tempuri.org/", "GetPnrPermissionSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/Getpnrpermission.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetPnrPermission.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/Getpnrpermission.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public GetPnrPermission(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetPnrPermission(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPnrPermission() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetPnrPermissionSoap
     */
    @WebEndpoint(name = "GetPnrPermissionSoap")
    public GetPnrPermissionSoap getGetPnrPermissionSoap() {
        return super.getPort(GetPnrPermissionSoap, GetPnrPermissionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPnrPermissionSoap
     */
    @WebEndpoint(name = "GetPnrPermissionSoap")
    public GetPnrPermissionSoap getGetPnrPermissionSoap(WebServiceFeature... features) {
        return super.getPort(GetPnrPermissionSoap, GetPnrPermissionSoap.class, features);
    }
    /**
     *
     * @return
     *     returns GetPnrPermissionSoap
     */
    @WebEndpoint(name = "GetPnrPermissionSoap12")
    public GetPnrPermissionSoap getGetPnrPermissionSoap12() {
        return super.getPort(GetPnrPermissionSoap12, GetPnrPermissionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPnrPermissionSoap
     */
    @WebEndpoint(name = "GetPnrPermissionSoap12")
    public GetPnrPermissionSoap getGetPnrPermissionSoap12(WebServiceFeature... features) {
        return super.getPort(GetPnrPermissionSoap12, GetPnrPermissionSoap.class, features);
    }

}
