package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-22T18:21:48.963+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "IssueBillAssignTo", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/IssueBillAssignTo.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class IssueBillAssignTo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "IssueBillAssignTo");
    public final static QName IssueBillAssignToSoap = new QName("http://tempuri.org/", "IssueBillAssignToSoap");
    public final static QName IssueBillAssignToSoap12 = new QName("http://tempuri.org/", "IssueBillAssignToSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/IssueBillAssignTo.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IssueBillAssignTo.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/IssueBillAssignTo.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public IssueBillAssignTo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IssueBillAssignTo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IssueBillAssignTo() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IssueBillAssignToSoap
     */
    @WebEndpoint(name = "IssueBillAssignToSoap")
    public IssueBillAssignToSoap getIssueBillAssignToSoap() {
        return super.getPort(IssueBillAssignToSoap, IssueBillAssignToSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IssueBillAssignToSoap
     */
    @WebEndpoint(name = "IssueBillAssignToSoap")
    public IssueBillAssignToSoap getIssueBillAssignToSoap(WebServiceFeature... features) {
        return super.getPort(IssueBillAssignToSoap, IssueBillAssignToSoap.class, features);
    }
    /**
     *
     * @return
     *     returns IssueBillAssignToSoap
     */
    @WebEndpoint(name = "IssueBillAssignToSoap12")
    public IssueBillAssignToSoap getIssueBillAssignToSoap12() {
        return super.getPort(IssueBillAssignToSoap12, IssueBillAssignToSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IssueBillAssignToSoap
     */
    @WebEndpoint(name = "IssueBillAssignToSoap12")
    public IssueBillAssignToSoap getIssueBillAssignToSoap12(WebServiceFeature... features) {
        return super.getPort(IssueBillAssignToSoap12, IssueBillAssignToSoap.class, features);
    }

}
