package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-29T15:20:48.970+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ModifyExchangeList", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/ModifyExchangeList.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class ModifyExchangeList extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ModifyExchangeList");
    public final static QName ModifyExchangeListSoap = new QName("http://tempuri.org/", "ModifyExchangeListSoap");
    public final static QName ModifyExchangeListSoap12 = new QName("http://tempuri.org/", "ModifyExchangeListSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/ModifyExchangeList.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ModifyExchangeList.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/ModifyExchangeList.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ModifyExchangeList(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ModifyExchangeList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModifyExchangeList() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ModifyExchangeListSoap
     */
    @WebEndpoint(name = "ModifyExchangeListSoap")
    public ModifyExchangeListSoap getModifyExchangeListSoap() {
        return super.getPort(ModifyExchangeListSoap, ModifyExchangeListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyExchangeListSoap
     */
    @WebEndpoint(name = "ModifyExchangeListSoap")
    public ModifyExchangeListSoap getModifyExchangeListSoap(WebServiceFeature... features) {
        return super.getPort(ModifyExchangeListSoap, ModifyExchangeListSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ModifyExchangeListSoap
     */
    @WebEndpoint(name = "ModifyExchangeListSoap12")
    public ModifyExchangeListSoap getModifyExchangeListSoap12() {
        return super.getPort(ModifyExchangeListSoap12, ModifyExchangeListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyExchangeListSoap
     */
    @WebEndpoint(name = "ModifyExchangeListSoap12")
    public ModifyExchangeListSoap getModifyExchangeListSoap12(WebServiceFeature... features) {
        return super.getPort(ModifyExchangeListSoap12, ModifyExchangeListSoap.class, features);
    }

}
