package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-22T17:30:22.198+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "OpenIssueOrderList", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/OpenIssueOrderList.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class OpenIssueOrderList extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OpenIssueOrderList");
    public final static QName OpenIssueOrderListSoap12 = new QName("http://tempuri.org/", "OpenIssueOrderListSoap12");
    public final static QName OpenIssueOrderListSoap = new QName("http://tempuri.org/", "OpenIssueOrderListSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/OpenIssueOrderList.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OpenIssueOrderList.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/OpenIssueOrderList.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public OpenIssueOrderList(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpenIssueOrderList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenIssueOrderList() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OpenIssueOrderListSoap
     */
    @WebEndpoint(name = "OpenIssueOrderListSoap12")
    public OpenIssueOrderListSoap getOpenIssueOrderListSoap12() {
        return super.getPort(OpenIssueOrderListSoap12, OpenIssueOrderListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenIssueOrderListSoap
     */
    @WebEndpoint(name = "OpenIssueOrderListSoap12")
    public OpenIssueOrderListSoap getOpenIssueOrderListSoap12(WebServiceFeature... features) {
        return super.getPort(OpenIssueOrderListSoap12, OpenIssueOrderListSoap.class, features);
    }
    /**
     *
     * @return
     *     returns OpenIssueOrderListSoap
     */
    @WebEndpoint(name = "OpenIssueOrderListSoap")
    public OpenIssueOrderListSoap getOpenIssueOrderListSoap() {
        return super.getPort(OpenIssueOrderListSoap, OpenIssueOrderListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenIssueOrderListSoap
     */
    @WebEndpoint(name = "OpenIssueOrderListSoap")
    public OpenIssueOrderListSoap getOpenIssueOrderListSoap(WebServiceFeature... features) {
        return super.getPort(OpenIssueOrderListSoap, OpenIssueOrderListSoap.class, features);
    }

}
