package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-29T10:20:38.363+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "RefundConfirm", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/RefundConfirm.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class RefundConfirm extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RefundConfirm");
    public final static QName RefundConfirmSoap = new QName("http://tempuri.org/", "RefundConfirmSoap");
    public final static QName RefundConfirmSoap12 = new QName("http://tempuri.org/", "RefundConfirmSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/RefundConfirm.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RefundConfirm.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/RefundConfirm.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public RefundConfirm(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RefundConfirm(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RefundConfirm() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RefundConfirmSoap
     */
    @WebEndpoint(name = "RefundConfirmSoap")
    public RefundConfirmSoap getRefundConfirmSoap() {
        return super.getPort(RefundConfirmSoap, RefundConfirmSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundConfirmSoap
     */
    @WebEndpoint(name = "RefundConfirmSoap")
    public RefundConfirmSoap getRefundConfirmSoap(WebServiceFeature... features) {
        return super.getPort(RefundConfirmSoap, RefundConfirmSoap.class, features);
    }
    /**
     *
     * @return
     *     returns RefundConfirmSoap
     */
    @WebEndpoint(name = "RefundConfirmSoap12")
    public RefundConfirmSoap getRefundConfirmSoap12() {
        return super.getPort(RefundConfirmSoap12, RefundConfirmSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundConfirmSoap
     */
    @WebEndpoint(name = "RefundConfirmSoap12")
    public RefundConfirmSoap getRefundConfirmSoap12(WebServiceFeature... features) {
        return super.getPort(RefundConfirmSoap12, RefundConfirmSoap.class, features);
    }

}
