package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-29T15:19:00.159+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "SearchExchangeList", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/SearchExchangeList.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class SearchExchangeList extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SearchExchangeList");
    public final static QName SearchExchangeListSoap = new QName("http://tempuri.org/", "SearchExchangeListSoap");
    public final static QName SearchExchangeListSoap12 = new QName("http://tempuri.org/", "SearchExchangeListSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/SearchExchangeList.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SearchExchangeList.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/SearchExchangeList.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SearchExchangeList(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SearchExchangeList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchExchangeList() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SearchExchangeListSoap
     */
    @WebEndpoint(name = "SearchExchangeListSoap")
    public SearchExchangeListSoap getSearchExchangeListSoap() {
        return super.getPort(SearchExchangeListSoap, SearchExchangeListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchExchangeListSoap
     */
    @WebEndpoint(name = "SearchExchangeListSoap")
    public SearchExchangeListSoap getSearchExchangeListSoap(WebServiceFeature... features) {
        return super.getPort(SearchExchangeListSoap, SearchExchangeListSoap.class, features);
    }
    /**
     *
     * @return
     *     returns SearchExchangeListSoap
     */
    @WebEndpoint(name = "SearchExchangeListSoap12")
    public SearchExchangeListSoap getSearchExchangeListSoap12() {
        return super.getPort(SearchExchangeListSoap12, SearchExchangeListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchExchangeListSoap
     */
    @WebEndpoint(name = "SearchExchangeListSoap12")
    public SearchExchangeListSoap getSearchExchangeListSoap12(WebServiceFeature... features) {
        return super.getPort(SearchExchangeListSoap12, SearchExchangeListSoap.class, features);
    }

}
