package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-29T15:36:08.180+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ConfirmRebookAmountService", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/ConfirmRebookAmountService.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class ConfirmRebookAmountService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ConfirmRebookAmountService");
    public final static QName ConfirmRebookAmountServiceSoap = new QName("http://tempuri.org/", "ConfirmRebookAmountServiceSoap");
    public final static QName ConfirmRebookAmountServiceSoap12 = new QName("http://tempuri.org/", "ConfirmRebookAmountServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/ConfirmRebookAmountService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConfirmRebookAmountService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/ConfirmRebookAmountService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ConfirmRebookAmountService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConfirmRebookAmountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConfirmRebookAmountService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ConfirmRebookAmountServiceSoap
     */
    @WebEndpoint(name = "ConfirmRebookAmountServiceSoap")
    public ConfirmRebookAmountServiceSoap getConfirmRebookAmountServiceSoap() {
        return super.getPort(ConfirmRebookAmountServiceSoap, ConfirmRebookAmountServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfirmRebookAmountServiceSoap
     */
    @WebEndpoint(name = "ConfirmRebookAmountServiceSoap")
    public ConfirmRebookAmountServiceSoap getConfirmRebookAmountServiceSoap(WebServiceFeature... features) {
        return super.getPort(ConfirmRebookAmountServiceSoap, ConfirmRebookAmountServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ConfirmRebookAmountServiceSoap
     */
    @WebEndpoint(name = "ConfirmRebookAmountServiceSoap12")
    public ConfirmRebookAmountServiceSoap getConfirmRebookAmountServiceSoap12() {
        return super.getPort(ConfirmRebookAmountServiceSoap12, ConfirmRebookAmountServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfirmRebookAmountServiceSoap
     */
    @WebEndpoint(name = "ConfirmRebookAmountServiceSoap12")
    public ConfirmRebookAmountServiceSoap getConfirmRebookAmountServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ConfirmRebookAmountServiceSoap12, ConfirmRebookAmountServiceSoap.class, features);
    }

}
