
package com.etrip8.airpay;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-07-08T21:11:44.291+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class PayServiceSoap_PayServiceSoap_Server{

    protected PayServiceSoap_PayServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PayServiceSoapImpl();
        String address = "http://airpay.etrip8.com/PayService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new PayServiceSoap_PayServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
