
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.etrip8.airpay;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-07-08T21:11:44.238+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "PayService",
                      portName = "PayServiceSoap",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://airpay.etrip8.com/PayService.asmx?WSDL",
                      endpointInterface = "com.etrip8.airpay.PayServiceSoap")
                      
public class PayServiceSoapImpl implements PayServiceSoap {

    private static final Logger LOG = Logger.getLogger(PayServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setOperatorContract(java.lang.String  sAccountNo ,)java.lang.String  sOperatorName ,)java.lang.String  sPwd ,)int  iDayNum ,)java.lang.String  sMaCode ,)boolean  bMaCode ,)java.lang.String  sSign )*
     */
    public java.lang.String setOperatorContract(java.lang.String sAccountNo,java.lang.String sOperatorName,java.lang.String sPwd,int iDayNum,java.lang.String sMaCode,boolean bMaCode,java.lang.String sSign) { 
        LOG.info("Executing operation setOperatorContract");
        System.out.println(sAccountNo);
        System.out.println(sOperatorName);
        System.out.println(sPwd);
        System.out.println(iDayNum);
        System.out.println(sMaCode);
        System.out.println(bMaCode);
        System.out.println(sSign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setTicketOrderToOrderXML(java.lang.String  ticketorderByxml ,)java.lang.String  sign )*
     */
    public java.lang.String setTicketOrderToOrderXML(java.lang.String ticketorderByxml,java.lang.String sign) { 
        LOG.info("Executing operation setTicketOrderToOrderXML");
        System.out.println(ticketorderByxml);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setPay(java.lang.String  version ,)java.lang.String  merId ,)java.lang.String  ordId ,)java.lang.String  gateId ,)java.lang.String  priv1 ,)java.lang.String  transAmt ,)java.lang.String  curyId ,)java.lang.String  transDate ,)java.lang.String  transType ,)java.lang.String  bgRetUrl ,)java.lang.String  pageRetUrl ,)java.lang.String  chkValue ,)java.lang.String  chinaPayUrl ,)java.lang.String  sign ,)java.lang.String  certSerial ,)com.etrip8.airpay.SetPay.Ticketorder  ticketorder )*
     */
    public java.lang.String setPay(java.lang.String version,java.lang.String merId,java.lang.String ordId,java.lang.String gateId,java.lang.String priv1,java.lang.String transAmt,java.lang.String curyId,java.lang.String transDate,java.lang.String transType,java.lang.String bgRetUrl,java.lang.String pageRetUrl,java.lang.String chkValue,java.lang.String chinaPayUrl,java.lang.String sign,java.lang.String certSerial,com.etrip8.airpay.SetPay.Ticketorder ticketorder) { 
        LOG.info("Executing operation setPay");
        System.out.println(version);
        System.out.println(merId);
        System.out.println(ordId);
        System.out.println(gateId);
        System.out.println(priv1);
        System.out.println(transAmt);
        System.out.println(curyId);
        System.out.println(transDate);
        System.out.println(transType);
        System.out.println(bgRetUrl);
        System.out.println(pageRetUrl);
        System.out.println(chkValue);
        System.out.println(chinaPayUrl);
        System.out.println(sign);
        System.out.println(certSerial);
        System.out.println(ticketorder);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#helloWorld(*
     */
    public java.lang.String helloWorld() { 
        LOG.info("Executing operation helloWorld");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setEPTEasyPayToOrderXML(java.lang.String  airCode ,)java.lang.String  b2BUser ,)java.lang.String  b2BPwd ,)java.lang.String  pnr ,)java.lang.String  orderID ,)java.lang.String  orderAmount ,)java.lang.String  sign ,)java.lang.String  certSerial ,)java.lang.String  ticketorderByxml )*
     */
    public java.lang.String setEPTEasyPayToOrderXML(java.lang.String airCode,java.lang.String b2BUser,java.lang.String b2BPwd,java.lang.String pnr,java.lang.String orderID,java.lang.String orderAmount,java.lang.String sign,java.lang.String certSerial,java.lang.String ticketorderByxml) { 
        LOG.info("Executing operation setEPTEasyPayToOrderXML");
        System.out.println(airCode);
        System.out.println(b2BUser);
        System.out.println(b2BPwd);
        System.out.println(pnr);
        System.out.println(orderID);
        System.out.println(orderAmount);
        System.out.println(sign);
        System.out.println(certSerial);
        System.out.println(ticketorderByxml);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setPayToOrderXMLForCZ(java.lang.String  merid ,)java.lang.String  orderno ,)java.lang.String  pnr ,)java.lang.String  billno ,)java.lang.String  bankcode ,)java.lang.String  currcode ,)java.lang.String  orderamount ,)java.lang.String  ordertype ,)java.lang.String  langtype ,)java.lang.String  bgreturl ,)java.lang.String  encodemsg ,)java.lang.String  signmsg ,)java.lang.String  sign ,)java.lang.String  certSerial ,)java.lang.String  ticketorderByxml )*
     */
    public java.lang.String setPayToOrderXMLForCZ(java.lang.String merid,java.lang.String orderno,java.lang.String pnr,java.lang.String billno,java.lang.String bankcode,java.lang.String currcode,java.lang.String orderamount,java.lang.String ordertype,java.lang.String langtype,java.lang.String bgreturl,java.lang.String encodemsg,java.lang.String signmsg,java.lang.String sign,java.lang.String certSerial,java.lang.String ticketorderByxml) { 
        LOG.info("Executing operation setPayToOrderXMLForCZ");
        System.out.println(merid);
        System.out.println(orderno);
        System.out.println(pnr);
        System.out.println(billno);
        System.out.println(bankcode);
        System.out.println(currcode);
        System.out.println(orderamount);
        System.out.println(ordertype);
        System.out.println(langtype);
        System.out.println(bgreturl);
        System.out.println(encodemsg);
        System.out.println(signmsg);
        System.out.println(sign);
        System.out.println(certSerial);
        System.out.println(ticketorderByxml);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setTicketOrder(com.etrip8.airpay.SetTicketOrder.Ticketorder  ticketorder ,)java.lang.String  sign )*
     */
    public java.lang.String setTicketOrder(com.etrip8.airpay.SetTicketOrder.Ticketorder ticketorder,java.lang.String sign) { 
        LOG.info("Executing operation setTicketOrder");
        System.out.println(ticketorder);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setPayToOrderXML(java.lang.String  version ,)java.lang.String  merId ,)java.lang.String  ordId ,)java.lang.String  gateId ,)java.lang.String  priv1 ,)java.lang.String  transAmt ,)java.lang.String  curyId ,)java.lang.String  transDate ,)java.lang.String  transType ,)java.lang.String  bgRetUrl ,)java.lang.String  pageRetUrl ,)java.lang.String  chkValue ,)java.lang.String  chinaPayUrl ,)java.lang.String  sign ,)java.lang.String  certSerial ,)java.lang.String  ticketorderByxml )*
     */
    public java.lang.String setPayToOrderXML(java.lang.String version,java.lang.String merId,java.lang.String ordId,java.lang.String gateId,java.lang.String priv1,java.lang.String transAmt,java.lang.String curyId,java.lang.String transDate,java.lang.String transType,java.lang.String bgRetUrl,java.lang.String pageRetUrl,java.lang.String chkValue,java.lang.String chinaPayUrl,java.lang.String sign,java.lang.String certSerial,java.lang.String ticketorderByxml) { 
        LOG.info("Executing operation setPayToOrderXML");
        System.out.println(version);
        System.out.println(merId);
        System.out.println(ordId);
        System.out.println(gateId);
        System.out.println(priv1);
        System.out.println(transAmt);
        System.out.println(curyId);
        System.out.println(transDate);
        System.out.println(transType);
        System.out.println(bgRetUrl);
        System.out.println(pageRetUrl);
        System.out.println(chkValue);
        System.out.println(chinaPayUrl);
        System.out.println(sign);
        System.out.println(certSerial);
        System.out.println(ticketorderByxml);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setAccountNoContract(java.lang.String  sAccountNo ,)java.lang.String  sPwd ,)int  iDayNum ,)java.lang.String  sMaCode ,)boolean  bMaCode ,)java.lang.String  sSign )*
     */
    public java.lang.String setAccountNoContract(java.lang.String sAccountNo,java.lang.String sPwd,int iDayNum,java.lang.String sMaCode,boolean bMaCode,java.lang.String sSign) { 
        LOG.info("Executing operation setAccountNoContract");
        System.out.println(sAccountNo);
        System.out.println(sPwd);
        System.out.println(iDayNum);
        System.out.println(sMaCode);
        System.out.println(bMaCode);
        System.out.println(sSign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setEPTEasyPay(java.lang.String  airCode ,)java.lang.String  b2BUser ,)java.lang.String  b2BPwd ,)java.lang.String  pnr ,)java.lang.String  orderID ,)java.lang.String  orderAmount ,)java.lang.String  sign ,)java.lang.String  certSerial ,)com.etrip8.airpay.SetEPTEasyPay.Ticketorder  ticketorder )*
     */
    public java.lang.String setEPTEasyPay(java.lang.String airCode,java.lang.String b2BUser,java.lang.String b2BPwd,java.lang.String pnr,java.lang.String orderID,java.lang.String orderAmount,java.lang.String sign,java.lang.String certSerial,com.etrip8.airpay.SetEPTEasyPay.Ticketorder ticketorder) { 
        LOG.info("Executing operation setEPTEasyPay");
        System.out.println(airCode);
        System.out.println(b2BUser);
        System.out.println(b2BPwd);
        System.out.println(pnr);
        System.out.println(orderID);
        System.out.println(orderAmount);
        System.out.println(sign);
        System.out.println(certSerial);
        System.out.println(ticketorder);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.etrip8.airpay.PayServiceSoap#setPayForCZ(java.lang.String  merid ,)java.lang.String  orderno ,)java.lang.String  pnr ,)java.lang.String  billno ,)java.lang.String  bankcode ,)java.lang.String  currcode ,)java.lang.String  orderamount ,)java.lang.String  ordertype ,)java.lang.String  langtype ,)java.lang.String  bgreturl ,)java.lang.String  encodemsg ,)java.lang.String  signmsg ,)java.lang.String  sign ,)java.lang.String  certSerial ,)com.etrip8.airpay.SetPayForCZ.Ticketorder  ticketorder )*
     */
    public java.lang.String setPayForCZ(java.lang.String merid,java.lang.String orderno,java.lang.String pnr,java.lang.String billno,java.lang.String bankcode,java.lang.String currcode,java.lang.String orderamount,java.lang.String ordertype,java.lang.String langtype,java.lang.String bgreturl,java.lang.String encodemsg,java.lang.String signmsg,java.lang.String sign,java.lang.String certSerial,com.etrip8.airpay.SetPayForCZ.Ticketorder ticketorder) { 
        LOG.info("Executing operation setPayForCZ");
        System.out.println(merid);
        System.out.println(orderno);
        System.out.println(pnr);
        System.out.println(billno);
        System.out.println(bankcode);
        System.out.println(currcode);
        System.out.println(orderamount);
        System.out.println(ordertype);
        System.out.println(langtype);
        System.out.println(bgreturl);
        System.out.println(encodemsg);
        System.out.println(signmsg);
        System.out.println(sign);
        System.out.println(certSerial);
        System.out.println(ticketorder);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
