package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-29T15:34:12.569+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "QueryRebookConfirmService", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/QueryRebookConfirm.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class QueryRebookConfirmService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryRebookConfirmService");
    public final static QName QueryRebookConfirmServiceSoap12 = new QName("http://tempuri.org/", "QueryRebookConfirmServiceSoap12");
    public final static QName QueryRebookConfirmServiceSoap = new QName("http://tempuri.org/", "QueryRebookConfirmServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/QueryRebookConfirm.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryRebookConfirmService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/QueryRebookConfirm.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public QueryRebookConfirmService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryRebookConfirmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryRebookConfirmService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QueryRebookConfirmServiceSoap
     */
    @WebEndpoint(name = "QueryRebookConfirmServiceSoap12")
    public QueryRebookConfirmServiceSoap getQueryRebookConfirmServiceSoap12() {
        return super.getPort(QueryRebookConfirmServiceSoap12, QueryRebookConfirmServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryRebookConfirmServiceSoap
     */
    @WebEndpoint(name = "QueryRebookConfirmServiceSoap12")
    public QueryRebookConfirmServiceSoap getQueryRebookConfirmServiceSoap12(WebServiceFeature... features) {
        return super.getPort(QueryRebookConfirmServiceSoap12, QueryRebookConfirmServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns QueryRebookConfirmServiceSoap
     */
    @WebEndpoint(name = "QueryRebookConfirmServiceSoap")
    public QueryRebookConfirmServiceSoap getQueryRebookConfirmServiceSoap() {
        return super.getPort(QueryRebookConfirmServiceSoap, QueryRebookConfirmServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryRebookConfirmServiceSoap
     */
    @WebEndpoint(name = "QueryRebookConfirmServiceSoap")
    public QueryRebookConfirmServiceSoap getQueryRebookConfirmServiceSoap(WebServiceFeature... features) {
        return super.getPort(QueryRebookConfirmServiceSoap, QueryRebookConfirmServiceSoap.class, features);
    }

}
