package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-22T18:38:55.949+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "SearchModifyOrderInfo", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/SearchModifyOrderInfo.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class SearchModifyOrderInfo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SearchModifyOrderInfo");
    public final static QName SearchModifyOrderInfoSoap12 = new QName("http://tempuri.org/", "SearchModifyOrderInfoSoap12");
    public final static QName SearchModifyOrderInfoSoap = new QName("http://tempuri.org/", "SearchModifyOrderInfoSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/SearchModifyOrderInfo.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SearchModifyOrderInfo.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/SearchModifyOrderInfo.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SearchModifyOrderInfo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SearchModifyOrderInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchModifyOrderInfo() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SearchModifyOrderInfoSoap
     */
    @WebEndpoint(name = "SearchModifyOrderInfoSoap12")
    public SearchModifyOrderInfoSoap getSearchModifyOrderInfoSoap12() {
        return super.getPort(SearchModifyOrderInfoSoap12, SearchModifyOrderInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchModifyOrderInfoSoap
     */
    @WebEndpoint(name = "SearchModifyOrderInfoSoap12")
    public SearchModifyOrderInfoSoap getSearchModifyOrderInfoSoap12(WebServiceFeature... features) {
        return super.getPort(SearchModifyOrderInfoSoap12, SearchModifyOrderInfoSoap.class, features);
    }
    /**
     *
     * @return
     *     returns SearchModifyOrderInfoSoap
     */
    @WebEndpoint(name = "SearchModifyOrderInfoSoap")
    public SearchModifyOrderInfoSoap getSearchModifyOrderInfoSoap() {
        return super.getPort(SearchModifyOrderInfoSoap, SearchModifyOrderInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchModifyOrderInfoSoap
     */
    @WebEndpoint(name = "SearchModifyOrderInfoSoap")
    public SearchModifyOrderInfoSoap getSearchModifyOrderInfoSoap(WebServiceFeature... features) {
        return super.getPort(SearchModifyOrderInfoSoap, SearchModifyOrderInfoSoap.class, features);
    }

}
