package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-22T18:36:54.850+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "IssueBillModify", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/IssueBillModify.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class IssueBillModify extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "IssueBillModify");
    public final static QName IssueBillModifySoap = new QName("http://tempuri.org/", "IssueBillModifySoap");
    public final static QName IssueBillModifySoap12 = new QName("http://tempuri.org/", "IssueBillModifySoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/IssueBillModify.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IssueBillModify.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/IssueBillModify.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public IssueBillModify(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IssueBillModify(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IssueBillModify() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IssueBillModifySoap
     */
    @WebEndpoint(name = "IssueBillModifySoap")
    public IssueBillModifySoap getIssueBillModifySoap() {
        return super.getPort(IssueBillModifySoap, IssueBillModifySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IssueBillModifySoap
     */
    @WebEndpoint(name = "IssueBillModifySoap")
    public IssueBillModifySoap getIssueBillModifySoap(WebServiceFeature... features) {
        return super.getPort(IssueBillModifySoap, IssueBillModifySoap.class, features);
    }
    /**
     *
     * @return
     *     returns IssueBillModifySoap
     */
    @WebEndpoint(name = "IssueBillModifySoap12")
    public IssueBillModifySoap getIssueBillModifySoap12() {
        return super.getPort(IssueBillModifySoap12, IssueBillModifySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IssueBillModifySoap
     */
    @WebEndpoint(name = "IssueBillModifySoap12")
    public IssueBillModifySoap getIssueBillModifySoap12(WebServiceFeature... features) {
        return super.getPort(IssueBillModifySoap12, IssueBillModifySoap.class, features);
    }

}
