package com.ctrip.ws.flights;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-29T10:18:36.121+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "RefundFeeConfirm", 
                  wsdlLocation = "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/RefundFeeConfirm.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class RefundFeeConfirm extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RefundFeeConfirm");
    public final static QName RefundFeeConfirmSoap = new QName("http://tempuri.org/", "RefundFeeConfirmSoap");
    public final static QName RefundFeeConfirmSoap12 = new QName("http://tempuri.org/", "RefundFeeConfirmSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/RefundFeeConfirm.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RefundFeeConfirm.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flights.ws.ctrip.com/Flight.Order.SupplierOpenAPI/RefundFeeConfirm.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public RefundFeeConfirm(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RefundFeeConfirm(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RefundFeeConfirm() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RefundFeeConfirmSoap
     */
    @WebEndpoint(name = "RefundFeeConfirmSoap")
    public RefundFeeConfirmSoap getRefundFeeConfirmSoap() {
        return super.getPort(RefundFeeConfirmSoap, RefundFeeConfirmSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundFeeConfirmSoap
     */
    @WebEndpoint(name = "RefundFeeConfirmSoap")
    public RefundFeeConfirmSoap getRefundFeeConfirmSoap(WebServiceFeature... features) {
        return super.getPort(RefundFeeConfirmSoap, RefundFeeConfirmSoap.class, features);
    }
    /**
     *
     * @return
     *     returns RefundFeeConfirmSoap
     */
    @WebEndpoint(name = "RefundFeeConfirmSoap12")
    public RefundFeeConfirmSoap getRefundFeeConfirmSoap12() {
        return super.getPort(RefundFeeConfirmSoap12, RefundFeeConfirmSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundFeeConfirmSoap
     */
    @WebEndpoint(name = "RefundFeeConfirmSoap12")
    public RefundFeeConfirmSoap getRefundFeeConfirmSoap12(WebServiceFeature... features) {
        return super.getPort(RefundFeeConfirmSoap12, RefundFeeConfirmSoap.class, features);
    }

}
